### ISSUE TITLE
cursor move problem on search window

### ISSUE THREAD

**Issue by dann** [c9s/cpan.vim#1]
Cursor moves down when I type 2 characters on search window.
so, I can't search the module based on the module name.
Any suggestions?

**Comment by c9s** [comment]
strange, it it in insert mode ? what character did you type ?
btw , i just fixed a exception catching problem , it cause the search window can't be opened.

**Comment by dann** [comment]
This problem occurs on both latest cpan.vim  and the first version of cpan.vim.
Characters are all ascii.  This problem isn't related the kind of characters because 
this problem occurs with any type of ascii characters,

What vim version do you use?
I use vim like below:

VIM - Vi IMproved 7.1 (2007 May 12, compiled May 11 2008 15:20:31)
MacOS X (unix) version

**Comment by dann** [comment]
The procedure to reproduce the problem is as follows:
1. press <C-c><C-v> in normal mode
2. type "any"

Cursor moves down when I type a and n and I can't type y on search window.

**Comment by dann** [comment]
This problems also occurs on Ubuntu 8.04. It seems this isn't MacOSX specific problem.

I uses vim below on Ubuntu.

VIM - Vi IMproved 7.1 (2007 May 12, compiled Jan 31 2008 12:00:11)
Included patches: 1-138
Compiled by buildd@rothera.buildd

**Comment by c9s** [comment]
my vim version is:

[Cornelius]$ vim --version
VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Oct 15 2009 00:26:07)
MacOS X (unix) version
Included patches: 1-264

i can't reproduce it on my vim.
does horizontal split reproduce this ? i mean   C-c C-m

**Comment by c9s** [comment]
i tried to reproduce on my ubuntu , but it doesnt work.

Linux Ironsea 2.6.28-14-generic #47-Ubuntu SMP Sat Jul 25 00:28:35 UTC 2009 i686 GNU/Linux

[ Ironsea :~/git-working/cpan.vim ]$ vim --version
VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Mar 19 2009 15:31:01)
Included patches: 1-79

**Comment by dann** [comment]
Horizonal split also reproduces this.

**Comment by dann** [comment]
This problem doesn't occured when I uninstalled another vim plugins and installed only cpan.vim. Iit seems another vim plugin conflicts cpan.vim.
I'll digg this problem later.

**Comment by dann** [comment]
I found autocomplpop.vim conflicted cpan.vim
http://www.vim.org/scripts/script.php?script_id=1879

I uninstalled it and this problem doesn't occur.

**Comment by c9s** [comment]
aha, because autocomplpop bind an autocmd to CursorMoveI , it's global , not buffer-only. so it conflcts. it seems i need to check if autocomplpop installed.

**Comment by c9s** [comment]
the CursorMoveI event handler in cpan.vim is buffer-only, so it will not affect other buffers. but we can't unhook a global event handler for just one buffer.

**Comment by c9s** [comment]
i have an idea, autocompop provides an Enable function for User to enable the autocompletion.
it's called ...

command! -bar -narg=0 AutoComplPopEnable  call s:Enable()
command! -bar -narg=0 AutoComplPopDisable call s:Disable()  

so , if we can detect if autocomplpop plugin is loaded , then we call Disable for cpan.vim search , after window closed , Enable it again.

**Comment by dann** [comment]
oh, cool !

**Comment by c9s** [comment]
i just fixed this. please try again. thanks :-)

**Comment by c9s** [comment]
it works for me. :p

**Comment by dann** [comment]
thank you, c9s.
it works well with autocomplpop. great!

**Comment by c9s** [comment]
so it will reveal autocomplpop after searching . great!
